import Recipe from "../src/models/recipe";

export const RECIPES = [
    new Recipe(
        "r1",
        "c1",
        "Pho",
        "https://www.allrecipes.com/thmb/SZjdgaXhmkrRNLoOvdxuAktwk3E=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/228443-authentic-pho-DDMFS-4x3-0523f6531ccf4dbeb4b5bde52e007b1e.jpg",
        5,
        [
            "500g beef or chicken, thinly sliced",
            "200g rice noodles",
            "1 onion, sliced",
            "2 cloves of garlic, minced",
            "1 cinnamon stick",
            "2 star anise",
            "2 tablespoons fish sauce",
            "Fresh herbs (Thai basil, cilantro, bean sprouts)",
            "Lime wedges",
            "Hoisin sauce and Sriracha (optional)",
        ],
        [
            "In a large pot, add sliced onion, minced garlic, cinnamon stick, and star anise. Toast them until fragrant.",
            "Add beef or chicken and cook until browned.",
            "Pour in water and bring to a boil. Skim off any impurities.",
            "Simmer the broth for at least 1 hour to develop flavors.",
            "Cook rice noodles according to package instructions.",
            "Arrange cooked noodles in bowls, top with sliced meat, and pour hot broth over them.",
            "Serve with fresh herbs, lime wedges, and condiments.",
        ],
        "1.5-2 hours",
    ),
    new Recipe(
        "r2",
        "c2",
        "Fresh Spring Rolls (Gỏi Cuốn)",
        "https://takestwoeggs.com/wp-content/uploads/2021/04/Vietnamese-Spring-Rolls-Recipee-Goi-Cuon-takes-two-eggs-easy-asian-fusion-recipes-sq.jpg",
        4,
        [
            "Rice paper wrappers",
            "Cooked shrimp or sliced tofu",
            "Rice vermicelli noodles",
            "Fresh herbs (mint, Thai basil)",
            "Lettuce leaves",
            "Bean sprouts",
            "Carrots, julienned",
            "Peanut dipping sauce",
        ],
        [
            "Dip a rice paper wrapper in warm water until soft and pliable.",
            "Place a lettuce leaf on the bottom half of the wrapper.",
            "Add a small handful of noodles, herbs, bean sprouts, carrots, and shrimp or tofu.",
            "Fold the sides inward and roll tightly.",
            "Repeat with remaining ingredients.",
            "Serve with peanut dipping sauce.",
        ],
        "30-45 minutes",
    ),
    new Recipe(
        "r3",
        "c3",
        "Tom Yum Soup",
        "https://upload.wikimedia.org/wikipedia/commons/e/e8/Tom_yam_kung_maenam.jpg",
        4,
        [
            "500g shrimp, peeled and deveined",
            "2 lemongrass stalks, bruised",
            "3 kaffir lime leaves",
            "2 tablespoons fish sauce",
            "1 tablespoon lime juice",
            "200g mushrooms, sliced",
            "2 - 3 Thai chilies, sliced(adjust to taste)",
            "1 small onion, sliced",
            "2 cloves of garlic, minced",
            "1 - inch piece of galangal or ginger, sliced",
            "Fresh cilantro for garnish",
        ],
        [
            "In a pot, bring water to a boil and add lemongrass, kaffir lime leaves, onion, garlic, and galangal or ginger.",
            "Simmer for 10-15 minutes to infuse flavors.",
            "Add shrimp, mushrooms, fish sauce, and Thai chilies.",
            "Cook until shrimp turns pink and opaque.",
            "Stir in lime juice and adjust seasoning if needed.",
            "Garnish with fresh cilantro and serve hot.",
        ],
        "30-40 minutes",
    ),
    new Recipe(
        "r4",
        "c4",
        "Caramelized Clay Pot Pork (Thịt Kho Tộ)",
        "https://poppysmack.com.au/wp-content/uploads/2021/10/Caramelised-salty-pork-1-scaled.jpg",
        5,
        [
            "500g pork belly, cut into bite-sized pieces",
            "3 tablespoons fish sauce",
            "3 tablespoons sugar",
            "1 tablespoon soy sauce",
            "1 tablespoon vegetable oil",
            "3 cloves of garlic, minced",
            "1 shallot, sliced",
            "Ground black pepper",
            "Chopped green onions for garnish",
        ],
        [
            "Heat oil in a clay pot or skillet over medium heat.",
            "Add minced garlic and shallots, sauté until fragrant.",
            "Add pork belly and cook until lightly browned.",
            "Stir in fish sauce, sugar, soy sauce, and black pepper.",
            "Reduce heat to low and simmer until pork is tender and caramelized.",
            "Garnish with chopped green onions and serve with steamed rice.",
        ],
        "1-1.5 hours",
    ),
    new Recipe(
        "r5",
        "c5",
        "Che Ba Mau (Three-Color Bean Dessert)",
        "https://helenrecipes.com/wp-content/uploads/2015/03/IMG_9091.jpg",
        4,
        [
            "200g mung beans, soaked and cooked",
            "200g red beans, soaked and cooked",
            "200g black-eyed peas, soaked and cooked",
            "400ml coconut milk",
            "200g palm sugar or brown sugar",
            "Crushed ice for serving",
        ],
        [
            "Divide cooked beans into three equal portions.",
            "In separate pots, add one portion of each bean with coconut milk and sugar.",
            "Simmer each pot until the beans are tender and well-coated in the syrup.",
            "Allow the mixtures to cool.",
            "In serving bowls, layer the beans, starting with red beans, then mung beans, and finally black-eyed peas.",
            "Serve with crushed ice.",
        ],
        "1-1.5 hours",
    ),
    new Recipe(
        "r6",
        "c6",
        "Bánh Mì (Vietnamese Sandwich)",
        "https://static.onecms.io/wp-content/uploads/sites/43/2023/01/31/roasted-pork-banh-mi-vietnamese-sandwitch-ddmfs-3X4-0332.jpg",
        5,
        [
            "Baguette or French bread",
            "Grilled or roasted meat (pork, chicken, or beef)",
            "Pickled vegetables (carrots, daikon radish)",
            "Cucumber, thinly sliced",
            "Fresh cilantro and jalapeño peppers",
            "Mayonnaise and soy sauce",
        ],
        [
            "Slice the baguette lengthwise and spread mayonnaise on both sides.",
            "Layer the grilled meat, pickled vegetables, cucumber, cilantro, and jalapeño.",
            "Drizzle with soy sauce if desired.",
            "Serve as a quick and flavorful sandwich.",
        ],
        "15-20 minutes",
    ),
    new Recipe(
        "r7",
        "c7",
        "Grilled Lemongrass Chicken (Gà Nướng Sả)",
        "https://upload.wikimedia.org/wikipedia/commons/b/b5/B%C3%BAn_with_Lemongrass_Chicken.jpg",
        4,
        [
            "500g chicken thighs or drumsticks",
            "3 stalks lemongrass, minced",
            "3 cloves of garlic, minced",
            "2 tablespoons fish sauce",
            "2 tablespoons soy sauce",
            "1 tablespoon honey or sugar",
            "1 tablespoon vegetable oil",
            "Ground black pepper",
            "Sliced scallions for garnish",
        ],
        [
            "In a bowl, combine lemongrass, garlic, fish sauce, soy sauce, honey or sugar, oil, and black pepper.",
            "Add chicken to the marinade and coat well. Let it marinate for at least 30 minutes.",
            "Preheat grill to medium-high heat.",
            "Grill chicken until cooked through and slightly charred, about 6-8 minutes per side.",
            "Garnish with sliced scallions and serve with steamed rice.",
        ],
        "40-50 minutes",
    ),
    new Recipe(
        "r8",
        "c8",
        "Caramelized Clay Pot Fish (Cá Kho Tộ)",
        "https://1.bp.blogspot.com/-8FWss8UDzgk/T6nJwf0UlJI/AAAAAAAAD2c/MWD5m2_xVj0/s1600/P1070946.JPG",
        4,
        [
            "500g catfish or basa fish fillets",
            "3 tablespoons fish sauce",
            "3 tablespoons sugar",
            "1 tablespoon vegetable oil",
            "3 cloves of garlic, minced",
            "1 shallot, sliced",
            "Ground black pepper",
            "Chopped green onions for garnish",
        ],
        [
            "In a clay pot or skillet, heat oil over medium heat.",
            "Add minced garlic and shallots, sauté until fragrant.",
            "Add fish fillets and cook until lightly browned.",
            "Stir in fish sauce, sugar, and black pepper.",
            "Reduce heat to low and simmer until the fish is tender and caramelized.",
            "Garnish with chopped green onions and serve with steamed rice.",
        ],
        "1-1.5 hours",
    ),
    new Recipe(
        "r9",
        "c9",
        "Tofu and Vegetable Stir-fry (Rau Xào Tàu Hủ)",
        "https://muingogai.ca/wp-content/uploads/2018/06/Seasonal-vegetables-and-crispy-tofu.png",
        4,
        [
            "200g firm tofu, cubed",
            "Assorted vegetables (broccoli, carrots, bell peppers, mushrooms)",
            "2 cloves of garlic, minced",
            "2 tablespoons soy sauce",
            "1 tablespoon hoisin sauce",
            "1 tablespoon vegetable oil",
            "Sesame seeds for garnish",
        ],
        [
            "Heat oil in a skillet or wok over medium-high heat.",
            "Add minced garlic and stir-fry for a minute.",
            "Add tofu and vegetables, stir-fry until vegetables are tender-crisp.",
            "In a small bowl, mix soy sauce and hoisin sauce together.",
            "Pour the sauce over the stir-fry and toss to coat evenly.",
            "Garnish with sesame seeds and serve with steamed rice.",
        ],
        "20-30 minutes",
    ),
    // new Recipe(
    //     "r10",
    //     "c1",
    //     "",
    //     "",
    //     "",
    //     [
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //     ],
    //     [
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //         "",
    //     ],
    //     "",
    // ),
]